"""
State Resolver & Canonicalization Engine

Resolves state dimension values to standard canonical names:
1. Case & Whitespace Normalization (BIHAR -> Bihar, punjab -> Punjab)
2. State Aliases & Abbreviations (UP -> Uttar Pradesh, UK -> Uttarakhand)
3. Indian City -> Indian State Resolution (Patna -> Bihar, Ludhiana -> Punjab, Gurgaon -> Haryana)
4. Foreign Locations -> INTERNATIONAL (Nepal, Dubai, USA -> INTERNATIONAL)
5. Unknown / Invalid Values -> UNMAPPED_STATE (NULL, numeric strings, garbage -> UNMAPPED_STATE)
"""

import re
from typing import Optional

CANONICAL_INDIAN_STATES = {
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman & Nicobar",
    "Chandigarh",
    "Dadra & Nagar Haveli and Daman & Diu",
    "Delhi",
    "Jammu & Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
}

# Explicit Lookup Map (Lowercased String -> Canonical Name)
STATE_LOOKUP = {
    # Exact Canonical Lowercase
    **{s.lower(): s for s in CANONICAL_INDIAN_STATES},
    # Common Abbreviations & Aliases
    "up": "Uttar Pradesh",
    "uttar pradesh": "Uttar Pradesh",
    "uttarpradesh": "Uttar Pradesh",
    "uttar pradesh ": "Uttar Pradesh",
    "pb": "Punjab",
    "punjab": "Punjab",
    "hr": "Haryana",
    "haryana": "Haryana",
    "bi": "Bihar",
    "bihar": "Bihar",
    "bihar state": "Bihar",
    "uk": "Uttarakhand",
    "uttarakhand": "Uttarakhand",
    "uttaranchal": "Uttarakhand",
    "hp": "Himachal Pradesh",
    "himachal": "Himachal Pradesh",
    "himachal pradesh": "Himachal Pradesh",
    "rj": "Rajasthan",
    "rajasthan": "Rajasthan",
    "jk": "Jammu & Kashmir",
    "j&k": "Jammu & Kashmir",
    "jammu and kashmir": "Jammu & Kashmir",
    "jammu & kashmir": "Jammu & Kashmir",
    "jh": "Jharkhand",
    "jharkhand": "Jharkhand",
    "wb": "West Bengal",
    "west bengal": "West Bengal",
    "bengal": "West Bengal",
    "mp": "Madhya Pradesh",
    "madhya pradesh": "Madhya Pradesh",
    "gj": "Gujarat",
    "gujarat": "Gujarat",
    "mh": "Maharashtra",
    "maharashtra": "Maharashtra",
    "ka": "Karnataka",
    "karnataka": "Karnataka",
    "tn": "Tamil Nadu",
    "tamil nadu": "Tamil Nadu",
    "ts": "Telangana",
    "telangana": "Telangana",
    "or": "Odisha",
    "orissa": "Odisha",
    "odisha": "Odisha",
    "as": "Assam",
    "assam": "Assam",
    "dl": "Delhi",
    "delhi": "Delhi",
    "ncr": "Delhi",
    "new delhi": "Delhi",
    "ch": "Chandigarh",
    "chandigarh": "Chandigarh",
    "cg": "Chhattisgarh",
    "chhattisgarh": "Chhattisgarh",
    "kl": "Kerala",
    "kerala": "Kerala",
    "ap": "Andhra Pradesh",
    "andhra pradesh": "Andhra Pradesh",

    # Known Indian Cities -> State
    "patna": "Bihar",
    "gaya": "Bihar",
    "muzaffarpur": "Bihar",
    "bhagalpur": "Bihar",
    "darbhanga": "Bihar",
    "purnia": "Bihar",
    "ludhiana": "Punjab",
    "amritsar": "Punjab",
    "jalandhar": "Punjab",
    "bathinda": "Punjab",
    "mohali": "Punjab",
    "patiala": "Punjab",
    "pathankot": "Punjab",
    "hoshiarpur": "Punjab",
    "phagwara": "Punjab",
    "gurgaon": "Haryana",
    "gurugram": "Haryana",
    "faridabad": "Haryana",
    "ambala": "Haryana",
    "rohtak": "Haryana",
    "panipat": "Haryana",
    "karnal": "Haryana",
    "hisar": "Haryana",
    "sonipat": "Haryana",
    "yamunanagar": "Haryana",
    "panchkula": "Haryana",
    "rewari": "Haryana",
    "lucknow": "Uttar Pradesh",
    "kanpur": "Uttar Pradesh",
    "agra": "Uttar Pradesh",
    "varanasi": "Uttar Pradesh",
    "noida": "Uttar Pradesh",
    "greater noida": "Uttar Pradesh",
    "ghaziabad": "Uttar Pradesh",
    "prayagraj": "Uttar Pradesh",
    "allahabad": "Uttar Pradesh",
    "gorakhpur": "Uttar Pradesh",
    "meerut": "Uttar Pradesh",
    "bareilly": "Uttar Pradesh",
    "aligarh": "Uttar Pradesh",
    "unnao": "Uttar Pradesh",
    "mathura": "Uttar Pradesh",
    "jhansi": "Uttar Pradesh",
    "ayodhya": "Uttar Pradesh",
    "moradabad": "Uttar Pradesh",
    "saharanpur": "Uttar Pradesh",
    "jaipur": "Rajasthan",
    "jodhpur": "Rajasthan",
    "kota": "Rajasthan",
    "udaipur": "Rajasthan",
    "bikaner": "Rajasthan",
    "ajmer": "Rajasthan",
    "alwar": "Rajasthan",
    "sikar": "Rajasthan",
    "shimla": "Himachal Pradesh",
    "dharamshala": "Himachal Pradesh",
    "mandi": "Himachal Pradesh",
    "solan": "Himachal Pradesh",
    "kullu": "Himachal Pradesh",
    "dehradun": "Uttarakhand",
    "haridwar": "Uttarakhand",
    "rishikesh": "Uttarakhand",
    "roorkee": "Uttarakhand",
    "haldwani": "Uttarakhand",
    "nainital": "Uttarakhand",
    "jammu": "Jammu & Kashmir",
    "srinagar": "Jammu & Kashmir",
    "anantnag": "Jammu & Kashmir",
    "ranchi": "Jharkhand",
    "dhanbad": "Jharkhand",
    "jamshedpur": "Jharkhand",
    "bokaro": "Jharkhand",
    "kolkata": "West Bengal",
    "howrah": "West Bengal",
    "siliguri": "West Bengal",
    "durgapur": "West Bengal",
    "asansol": "West Bengal",
    "bhopal": "Madhya Pradesh",
    "indore": "Madhya Pradesh",
    "gwalior": "Madhya Pradesh",
    "jabalpur": "Madhya Pradesh",
    "ujjain": "Madhya Pradesh",
    "ahmedabad": "Gujarat",
    "surat": "Gujarat",
    "vadodara": "Gujarat",
    "rajkot": "Gujarat",
    "mumbai": "Maharashtra",
    "pune": "Maharashtra",
    "nagpur": "Maharashtra",
    "nashik": "Maharashtra",
    "thane": "Maharashtra",
    "navi mumbai": "Maharashtra",
    "bengaluru": "Karnataka",
    "bangalore": "Karnataka",
    "mysore": "Karnataka",
    "mangalore": "Karnataka",
    "chennai": "Tamil Nadu",
    "coimbatore": "Tamil Nadu",
    "madurai": "Tamil Nadu",
    "hyderabad": "Telangana",
    "warangal": "Telangana",
    "bhubaneswar": "Odisha",
    "cuttack": "Odisha",
    "rourkela": "Odisha",
    "guwahati": "Assam",
    "silchar": "Assam",
    "dibrugarh": "Assam",
}

# Known International Foreign Locations
FOREIGN_LOCATIONS = {
    "nepal",
    "bhutan",
    "bangladesh",
    "uae",
    "dubai",
    "abu dhabi",
    "usa",
    "united states",
    "us",
    "canada",
    "uk",
    "united kingdom",
    "london",
    "australia",
    "kuwait",
    "qatar",
    "oman",
    "saudi arabia",
    "ksa",
    "nigeria",
    "kenya",
    "afghanistan",
    "sri lanka",
    "singapore",
    "malaysia",
    "japan",
    "germany",
    "france",
    "china",
    "thailand",
    "indonesia",
    "maldives",
    "bahrain",
    "muscat",
    "kathmandu",
    "pokhara",
    "dhaka",
    "thimphu",
    "colombo",
    "lagos",
    "nairobi",
    "kabul",
    "toronto",
    "vancouver",
    "sydney",
    "melbourne",
    "international",
}


def resolve_state(raw_state: Optional[str]) -> str:
    """
    Resolve raw state string to canonical state name, INTERNATIONAL, or UNMAPPED_STATE.
    """
    if not raw_state or not isinstance(raw_state, str):
        return "UNMAPPED_STATE"

    cleaned = raw_state.strip()
    if not cleaned or cleaned.isdigit():
        return "UNMAPPED_STATE"

    norm_key = cleaned.lower()

    # Check Direct Lookup (States, Aliases, Indian Cities)
    if norm_key in STATE_LOOKUP:
        return STATE_LOOKUP[norm_key]

    # Check International Locations
    if norm_key in FOREIGN_LOCATIONS:
        return "INTERNATIONAL"

    # Fuzzy/Substring checks for known names
    for key, canonical in STATE_LOOKUP.items():
        if len(key) > 3 and key == norm_key:
            return canonical

    # Non-recognized / Garbage / Unknown -> UNMAPPED_STATE
    return "UNMAPPED_STATE"
